workflows:
  build-alrc-radio-app:
    name: Build ALRC Radio App APK
    max_build_duration: 60
    environment:
      flutter: stable
      #android_signing:
      #  keystore_reference: keystore_reference_id
      vars:                  
        PACKAGE_NAME: "com.alrc.radio"
    scripts:
      - name: 🔄 Get dependencies
          script: |
            flutter pub get
      - name: ⚙️ Build APK
          script: |
            flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients
          - yetotodeabdelr@gmail.com